version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 'Abcd#1234'  # Encadrez la valeur par des guillemets simples
      MYSQL_DATABASE: gestion-employe-db
    ports:
      - "3306:3306"
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin-container
    environment:
      PMA_HOST: my-mysql-container
      PMA_USER: root
      PMA_PASSWORD: 'Abcd#1234'  # Encadrez la valeur par des guillemets simples
    ports:
      - "8080:80"
