version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ''  # Laissez le mot de passe vide
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
